### ISSUE TITLE
Jade as Rails views

### ISSUE THREAD

**Issue by zohararad** [inossidabile/jade#2]
Hey Boris

I forked your wonderful gem and added capability to render Jade templates as Rails views. So basically, you can share your views completely between client and server.

I'm wondering if you'd like to merge this capability into your gem or would you prefer to keep these capabilities separate.

Feel free to check the code on https://github.com/zohararad/jade

Zohar

**Comment by inossidabile** [comment]
Could you please explain how exactly did you make it work?

**Comment by zohararad** [comment]
Sure

Rendering flow goes like this:
- Call to Jade::Renderer.call prepares controller instance variables and calls Jade::Renderer.convert_template with these variables
- Jade::Renderer.convert_template in turn takes controller variables and passes them to Jade::Compiler.render which does the following:
  1. Combine template text with Jade mixins (more on that below)
  2. Precompile template with ExecJS context (Jade::Compiler.context)
  3. Call template in context passing it the Jade runtime source, any included Javascripts and serialized variables

To allow better support for client-side code on the server, you can configure the gem with two parameters:
1. Jade::Configuration.mixins_path - will look for jade mixins in that path, and include them in the view rendering flow. Inclusion is similar to Rails - always add application_mixin.jade and then add controller's mixin (so for posts_controller, add posts_mixin.jade)
2. Jade::Configuration.includes - an array of Javascript strings that contains code the template needs to properly render. A good example would be using I18n.js. So in the browser, you simply include that file and you have I18n capabilities. To make it work on the server, you simply pass the source of that file to the Jade::Configuration.includes array and the rendering process will make the code available when evaluating the template.

Finally, there's the issue of properly serializing ruby / rails variables for use inside the template. Here I based a lot of logic on Ice - https://github.com/ludicast/ice .

The basic idea is this to serialize the variables passed to the Jade template into JSON. To support recursive serializing of ActiveModel::Relations or non-primitive types that can be serialized, I did two things
1. Extend ruby's Hash, Array, Object classes to support a "to_jade" method that tries to recursively call "to_jade" on members (In the case of Object class, its only called when the object responds to the "to_a" method)
2. Add a mixin that can be used inside ActiveRecord classes, that defines which instance attributes are serialized when the "to_jade" method is called on an instance. This allows for fine-grained control over how an AR / AM object is serialized into JSON.

The serializing flow is basically a recursive attempt to convert a ruby variable to a hash / array and then to JSON from there. Serializing logic is lib/jade/serializer.rb

**Comment by inossidabile** [comment]
This definitely should be kept at your repo for two reasons: I don't use Jade any more and the fork is too massive. However I should tell you, I was moving into the same direction. Are there any ways for me to get in contact with you besides this issue?

**Comment by zohararad** [comment]
My initial reason for not simply sending a pull request was that i thought my addition to your code was too big and perhaps out of context. I'll keep the fork as a separate gem as you advised and hope others can benefit from it :)

Feel free to talk to me on @zohararad (Twitter) or zohar@zohararad.com (Email)

Zohar
